name: Build and Release Installer

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows for building the installer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x  # Change to your app's .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet build --configuration Release --no-restore

      - name: Publish the Application
        run: dotnet publish -c Release -o publish

      - name: Create Installer
        run: |
          echo "Creating installer..."
          # Replace this with your actual installer command
          # Example for Inno Setup:
          # iscc path/to/your/installer_script.iss

      - name: Auto Generate Tag
        id: tag
        shell: pwsh
        run: |
          $timestamp = Get-Date -UFormat "%s"  # Get Unix timestamp
          $NEW_TAG = "v1.0.$timestamp"
          echo "NEW_TAG=$NEW_TAG" | Out-File -FilePath $env:GITHUB_ENV -Append
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4  # Fixed version issue
        with:
          name: LookawayApp_Installer
          path: publish/LookawayApp_Installer.exe  # Ensure this path is correct

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.NEW_TAG }}  # Uses the new tag we generated
          files: publish/LookawayApp_Installer.exe
