name: Release LookawayApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we fetch all tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.202'  # Exact version you specified

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build -c Release

      - name: Run tests
        run: dotnet test -c Release --no-build

      - name: Publish application
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o release/

      - name: Generate new version tag
        id: versioning
        shell: pwsh
        run: |
          git fetch --tags
          
          # Get latest tag (if no tag, default to v0.0.0)
          $LATEST_TAG = git tag --sort=-v:refname | Select-Object -First 1
          if (-not $LATEST_TAG) { $LATEST_TAG = "v0.0.0" }
          echo "Latest tag: $LATEST_TAG"

          # Extract version numbers
          $MAJOR, $MINOR, $PATCH = $LATEST_TAG -replace "v", "" -split "\."
          $NEW_PATCH = [int]$PATCH + 1
          $NEW_TAG = "v$MAJOR.$MINOR.$NEW_PATCH"
          
          echo "NEW_TAG=$NEW_TAG" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "Generated new tag: $NEW_TAG"

      - name: Create Git Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ steps.versioning.outputs.NEW_TAG }}
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/foundRamit/LookAwayApp.git
          git push origin ${{ steps.versioning.outputs.NEW_TAG }}

      - name: ZIP Application
        shell: pwsh
        run: |
          Compress-Archive -Path release/* -DestinationPath LookawayApp_${{ steps.versioning.outputs.NEW_TAG }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LookawayApp
          path: LookawayApp_${{ steps.versioning.outputs.NEW_TAG }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: LookawayApp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.NEW_TAG }}
          name: Release ${{ needs.build.outputs.NEW_TAG }}
          draft: false
          prerelease: false
          files: LookawayApp_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}