name: Release LookawayApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      PROJECT_PATH: LookawayApp/LookawayApp.csproj

    outputs:
      NEW_TAG: ${{ steps.versioning.outputs.NEW_TAG }}  # ✅ Expose NEW_TAG to other jobs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.202'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build application
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release

      - name: Publish application
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:PublishTrimmed=false `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -o release/

      - name: Generate version tag
        id: versioning  # ✅ Use 'id' so we can refer to 'outputs'
        shell: pwsh
        run: |
          git fetch --tags
          $LATEST_TAG = git tag --sort=-v:refname | Select-Object -First 1
          if (-not $LATEST_TAG) { $LATEST_TAG = "v0.0.0" }
          
          $MAJOR, $MINOR, $PATCH = $LATEST_TAG -replace "v", "" -split "\."
          $NEW_PATCH = [int]$PATCH + 1
          $NEW_TAG = "v$MAJOR.$MINOR.$NEW_PATCH"
          
          echo "NEW_TAG=$NEW_TAG" | Out-File -FilePath $env.GITHUB_ENV -Append
          echo "NEW_TAG=$NEW_TAG" >> $env.GITHUB_OUTPUT  # ✅ Store as an output
          echo "Generated new tag: $NEW_TAG"

      - name: Create Git Tag and Push
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git tag ${{ steps.versioning.outputs.NEW_TAG }}
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/foundRamit/LookAwayApp.git ${{ steps.versioning.outputs.NEW_TAG }}

      - name: ZIP Application
        shell: pwsh
        run: |
          Compress-Archive -Path release/* -DestinationPath LookawayApp_${{ steps.versioning.outputs.NEW_TAG }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LookawayApp
          path: LookawayApp_${{ steps.versioning.outputs.NEW_TAG }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: LookawayApp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.NEW_TAG }}  # ✅ Now correctly gets NEW_TAG
          name: Release ${{ needs.build.outputs.NEW_TAG }}
          draft: false
          prerelease: false
          files: LookawayApp_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
