name: Build and Release Installer

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows for building the installer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x  # Change to your app's .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet build --configuration Release --no-restore

      - name: Publish the Application
        run: dotnet publish -c Release -o publish

      - name: Create Installer with Inno Setup
        run: |
          # Download and install Inno Setup
          choco install innosetup -y
          
          # Create an Inno Setup script (save as setup.iss)
          @"
          [Setup]
          AppName=Lookaway App
          AppVersion=1.0.0  # Replace with your actual version
          DefaultDirName={pf}\LookawayApp
          OutputBaseFilename=LookawayAppInstaller
          OutputDir=publish
          DefaultGroupName=Lookaway App
          UninstallDisplayIcon={app}\LookawayApp.exe

          [Files]
          Source: 'publish\*'; DestDir: '{app}'; Flags: recursesubdirs

          [Tasks]
          Name: desktopicon; Description: Create a desktop icon; GroupDescription: Additional icons

          [Icons]
          Name: "{group}\Lookaway App"; Filename: "{app}\LookawayApp.exe"
          Name: "{group}\Uninstall Lookaway App"; Filename: "{uninstallexe}"
          Name: "{commondesktop}\Lookaway App"; Filename: "{app}\LookawayApp.exe"; Tasks: desktopicon

          [Run]
          Filename: "{app}\LookawayApp.exe"; Description: "Launch Lookaway App"; Flags: postinstall nowait skipifsilent
          "@ | Out-File -FilePath publish\setup.iss

          # Compile the Inno Setup script
          iscc publish\setup.iss