name: Release LookawayApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we fetch all tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.202'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet publish -c Release -r win-x64 --self-contained true -o release/

      - name: Generate new version tag
        id: versioning
        shell: pwsh
        run: |
          git fetch --tags
          
          # Get latest tag (if no tag, default to v0.0.0)
          $LATEST_TAG = git tag --sort=-v:refname | Select-Object -First 1
          if (-not $LATEST_TAG) { $LATEST_TAG = "v0.0.0" }
          echo "Latest tag: $LATEST_TAG"

          # Extract version numbers
          $MAJOR, $MINOR, $PATCH = $LATEST_TAG -replace "v", "" -split "\."
          $NEW_TAG = "v$MAJOR.$MINOR.$($PATCH + 1)"
          echo "NEW_TAG=$NEW_TAG" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Generated new tag: $NEW_TAG"

      - name: Check GitHub Token Permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user

      - name: Create Git Tag and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $env:NEW_TAG
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/foundRamit/LookAwayApp.git $env:NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LookawayApp
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: LookawayApp
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          draft: false
          prerelease: false
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
