name: Release LookawayApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet publish -c Release -r win-x64 --self-contained true -o release/

      - name: Generate new version tag
        id: versioning
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          NEW_TAG="v$(echo $LATEST_TAG | cut -d'.' -f1).$(echo $LATEST_TAG | cut -d'.' -f2).$(( $(echo $LATEST_TAG | cut -d'.' -f3) + 1 ))"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: LookawayApp
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: LookawayApp
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          draft: false
          prerelease: false
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
